name: Build Binaries

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            name: linux
            arch: amd64
          # TODO: Uncomment when repository is public
          # - os: ubuntu-24.04-arm
          #   name: linux-arm
          #   arch: arm64
          - os: windows-latest  
            name: windows
            arch: amd64
          - os: macos-latest
            name: macos
            arch: arm64

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
    - name: Build binary
      shell: bash
      run: |
        uv sync
        uv run build.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bzm-mcp-${{ matrix.name }}-${{ matrix.arch }}
        path: dist/
        
    - name: Commit artifacts to repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main  # Get latest changes to avoid race conditions due to OSs matrix running in parallel
        git add dist/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "[skip ci] Update bzm-mcp-${{ matrix.name }}-${{ matrix.arch }} binary"
          git push origin main
        fi